DROP TABLE IF EXISTS Jasen CASCADE;
DROP TABLE IF EXISTS Hallitus CASCADE;
DROP TABLE IF EXISTS Hallitus_has_Jasen;
DROP TABLE IF EXISTS Kokous CASCADE;
DROP TABLE IF EXISTS Kokous_has_Jasen;
DROP TABLE IF EXISTS Dokumentti CASCADE;
DROP TABLE IF EXISTS Jasenmaksu CASCADE;
DROP TABLE IF EXISTS Jasen_has_Jasenmaksu;